meta:
  description: 'toggle about xYZ'
  tags:
    - Foo
default:
  ttl: 120s
  value: 
      data: false
      type: boolean

configurations:
  - config: 
    id: 1
    rulesBehaviour: "AND"
    rules:
      paltform:
        - android
        - web
      version:
        min: "1.0.1"
        max: "9.0.0"
      country:
        - ES
      city:
        - BCN
        - MAD
      userId:
        - 4234234234Z
        - X2342342342
        - 45677u45643
      userGroup: 
        - admin
        - staff
        - testers
        
    rollout:
      enabledForOnly: 0.10

    value: true

  - config: 
    id: 2
    rulesBehaviour: "OR"
    rules:
      city:
        - BCN
      country:
        - FR
      timer: 
        triggerTime: "Jan 2, 2021 at 3:04pm (MST)"  

    rollout:
      enabledForOnly: 0.10
    
    value: true
